---
title: "Functions"
output: html_document
date: "2025-12-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Import required Libraries through the requirements.R file and import uncleaned data.
```{r include=FALSE}
source("00_requirements.R")
uncleanData <- read_tsv("participants.tsv")
```

Data Cleaning
```{r}
cleanData <- uncleanData[,!names(uncleanData) %in% c("HbA1c", "sex", "bodyweight")]
names(cleanData)[names(cleanData) == "fasting insulin"] <- "Fasting Insulin"
names(cleanData)[names(cleanData) == "age"] <- "Age"
names(cleanData)[names(cleanData) == "participant_id"] <- "Participant_ID"

cleanData$HOMA <- as.double(cleanData$HOMA)
cleanData <- na.omit(cleanData)

print(cleanData)
```


Variables

```{r}
HOMA_vals <- c(cleanData$HOMA)
na.omit(HOMA_vals)
BMI_vals <- c(cleanData$BMI)
age_vals <- c(cleanData$Age)
fast_insulin_vals <- c(cleanData$`Fasting Insulin`)
```

Plots and Correlation Testing


Age vs HOMA
```{r}
plot(cleanData$Age, cleanData$HOMA, xlab = "Age", ylab = "HOMA", main = "Age vs HOMA", sub = "Figure 1: How age is related to HOMA")
abline(h = 2.5, col = 'red')

cor.test(age_vals, HOMA_vals)
```

Age vs BMI
```{r}
plot(cleanData$Age, cleanData$BMI, xlab = "Age", ylab = "BMI", main = "BMI vs Age", sub = "Figure 2: How age is related to BMI")
abline(h = 25, col = 'red')

cor.test(age_vals, BMI_vals)
```

BMI vs HOMA
```{r}
plot(cleanData$BMI, cleanData$HOMA, xlab = "BMI", ylab = "HOMA", main = "HOMA vs BMI", sub = "Figure 3: How BMI is related to HOMA")
segments(x0 = 25, y0 = 0, x1 = 25, y1 = 2.5, col = 'red')
segments(x0 = 0, y0 = 2.5, x1 = 25, y1 = 2.5, col = 'red')

cor.test(BMI_vals, HOMA_vals)
```

Fasting Insulin vs HOMA
```{r}
plot(cleanData$`Fasting Insulin`, cleanData$HOMA, xlab = "Fasting Insulin", ylab = "HOMA vs Fasting Insulin", sub = "Figure 4: How fasting insulin is related to HOMA")

cor.test(fast_insulin_vals, HOMA_vals)
```


